In [25]:
import pandas as pd
import numpy as np

In [26]:
df1 = pd.read_excel('data/시도_산업_규모별_임금_및_근로시간_상용근로자_5인이상_사업체_2015-2019.xlsx')
df2 = pd.read_excel('data/시도_산업_규모별_임금_및_근로시간_상용근로자_5인이상_사업체_2020-2022.xlsx')
df3 = pd.read_excel('data/시도_산업_규모별_임금_및_근로시간_상용근로자_5인이상_사업체_2023-2025.xlsx')

In [27]:
ddf = pd.concat([df1,df2,df3], axis=0)
ddf.to_csv('5인이상사업체상용근로자월평균임금.csv')

In [28]:
df = pd.read_csv('./5인이상사업체상용근로자월평균임금.csv', index_col='Unnamed: 0')
df

      연도 행정구역  상용월급여액(원)  상용정액급여(원)  상용초과급여(원)  상용특별급여(원)
0   2015   전국    2926186    2710026     216160     378678
1   2015   서울    3261561    3169585      91976     446444
2   2015   부산    2620611    2446981     173631     295399
3   2015   대구    2415995    2231900     184095     262429
4   2015   인천    2723424    2499996     223427     301651
..   ...  ...        ...        ...        ...        ...
49  2025   전북    3475789    3202598     273191     339361
50  2025   전남    3791086    3484960     306126     459410
51  2025   경북    3920655    3531001     389654     431569
52  2025   경남    3906168    3518751     387417     354733
53  2025   제주    3289535    3148603     140932     286156

[193 rows x 6 columns]

$$지역별 임금수준 = 상용월급여액(원) + 상용특별급여(원)$$

In [29]:
df.insert(2, '상용월평균급여(원)', df['상용월급여액(원)']+df['상용특별급여(원)'])

In [30]:
df

      연도 행정구역  상용월평균급여(원)  상용월급여액(원)  상용정액급여(원)  상용초과급여(원)  상용특별급여(원)
0   2015   전국     3304864    2926186    2710026     216160     378678
1   2015   서울     3708005    3261561    3169585      91976     446444
2   2015   부산     2916010    2620611    2446981     173631     295399
3   2015   대구     2678424    2415995    2231900     184095     262429
4   2015   인천     3025075    2723424    2499996     223427     301651
..   ...  ...         ...        ...        ...        ...        ...
49  2025   전북     3815150    3475789    3202598     273191     339361
50  2025   전남     4250496    3791086    3484960     306126     459410
51  2025   경북     4352224    3920655    3531001     389654     431569
52  2025   경남     4260901    3906168    3518751     387417     354733
53  2025   제주     3575691    3289535    3148603     140932     286156

[193 rows x 7 columns]

In [31]:
sido = {
'전국' : '전국',
'서울' : '서울특별시',
'부산' : '부산광역시',
'대구' : '대구광역시',
'인천' : '인천광역시',
'광주' : '광주광역시',
'대전' : '대전광역시',
'울산' : '울산광역시',
'세종' : '세종특별자치시',
'경기' : '경기도',
'강원' : '강원특별자치도',
'충북' : '충청북도',
'충남' : '충청남도',
'전북' : '전북특별자치도',
'전남' : '전라남도',
'경북' : '경상북도',
'경남' : '경상남도',
'제주' : '제주특별자치도'
}

In [32]:
df.replace({'행정구역': sido}, inplace=True)

In [33]:
df

      연도     행정구역  상용월평균급여(원)  상용월급여액(원)  상용정액급여(원)  상용초과급여(원)  상용특별급여(원)
0   2015       전국     3304864    2926186    2710026     216160     378678
1   2015    서울특별시     3708005    3261561    3169585      91976     446444
2   2015    부산광역시     2916010    2620611    2446981     173631     295399
3   2015    대구광역시     2678424    2415995    2231900     184095     262429
4   2015    인천광역시     3025075    2723424    2499996     223427     301651
..   ...      ...         ...        ...        ...        ...        ...
49  2025  전북특별자치도     3815150    3475789    3202598     273191     339361
50  2025     전라남도     4250496    3791086    3484960     306126     459410
51  2025     경상북도     4352224    3920655    3531001     389654     431569
52  2025     경상남도     4260901    3906168    3518751     387417     354733
53  2025  제주특별자치도     3575691    3289535    3148603     140932     286156

[193 rows x 7 columns]

In [34]:
df.to_csv('5인이상사업체상용근로자월평균급여.csv')

In [35]:
df.to_csv('encoding5인이상사업체상용근로자월평균급여.csv', encoding='cp949')

In [36]:
sejongdf = pd.read_csv('encoding5인이상사업체상용근로자월평균급여.csv', encoding='cp949')

In [37]:
sejongdf

,Unnamed: 0,연도,행정구역,상용월평균급여(원),상용월급여액(원),상용정액급여(원),상용초과급여(원),상용특별급여(원)
0,0,2015,전국,3304864,2926186,2710026,216160,378678
1,1,2015,서울특별시,3708005,3261561,3169585,91976,446444
2,2,2015,부산광역시,2916010,2620611,2446981,173631,295399
3,3,2015,대구광역시,2678424,2415995,2231900,184095,262429
4,4,2015,인천광역시,3025075,2723424,2499996,223427,301651
...,...,...,...,...,...,...,...,...
188,49,2025,전북특별자치도,3815150,3475789,3202598,273191,339361
189,50,2025,전라남도,4250496,3791086,3484960,306126,459410
190,51,2025,경상북도,4352224,3920655,3531001,389654,431569
191,52,2025,경상남도,4260901,3906168,3518751,387417,354733
192,53,2025,제주특별자치도,3575691,3289535,3148603,140932,286156

In [38]:
df

      연도     행정구역  상용월평균급여(원)  상용월급여액(원)  상용정액급여(원)  상용초과급여(원)  상용특별급여(원)
0   2015       전국     3304864    2926186    2710026     216160     378678
1   2015    서울특별시     3708005    3261561    3169585      91976     446444
2   2015    부산광역시     2916010    2620611    2446981     173631     295399
3   2015    대구광역시     2678424    2415995    2231900     184095     262429
4   2015    인천광역시     3025075    2723424    2499996     223427     301651
..   ...      ...         ...        ...        ...        ...        ...
49  2025  전북특별자치도     3815150    3475789    3202598     273191     339361
50  2025     전라남도     4250496    3791086    3484960     306126     459410
51  2025     경상북도     4352224    3920655    3531001     389654     431569
52  2025     경상남도     4260901    3906168    3518751     387417     354733
53  2025  제주특별자치도     3575691    3289535    3148603     140932     286156

[193 rows x 7 columns]

In [39]:
df[df['행정구역'] != '전국'].reset_index(drop=True).to_csv('pre_data/pre_산업일자리_임금수준.csv')

2015~2019년까지 세종시 데이터 미분류로 인한 결측치 보충 작업

In [40]:
# 1. 채워야 할 컬럼 목록 정의 (숫자 데이터만)
target_cols = ['상용월평균급여(원)', '상용월급여액(원)', '상용정액급여(원)', '상용초과급여(원)', '상용특별급여(원)']

# 2. 보정 비율 계산 및 결측치 채우기 함수
def fill_missing_sejong(sejongdf, cols):
    df_filled = sejongdf.copy()
    
    # 충남 데이터 미리 뽑아두기 (속도 향상)
    chungnam_df = sejongdf[sejongdf['행정구역'] == '충청남도'].set_index('연도')
    
    for col in cols:
        # (1) 2020년 이후 데이터로 '세종 vs 충남' 비율 계산
        mean_chungnam = sejongdf[(sejongdf['행정구역'] == '충청남도') & (sejongdf['연도'] >= 2020)][col].mean()
        mean_sejong = sejongdf[(sejongdf['행정구역'] == '세종특별자치시') & (sejongdf['연도'] >= 2020)][col].mean()
        
        ratio = mean_sejong / mean_chungnam
        print(f"[{col}] 보정 비율: {ratio:.4f}")  # 비율 확인용 출력

        # (2) 세종시의 빈 값 찾아서 채우기
        # 조건: 세종시이면서 + 해당 컬럼이 비어있는 경우
        mask = (df_filled['행정구역'] == '세종특별자치시') & (df_filled[col].isna())
        
        # 빈 곳의 '연도'를 가져와서 -> 충남의 해당 연도 값 * 비율 적용
        # map 함수를 쓰면 반복문 없이 한 번에 처리가 가능합니다
        df_filled.loc[mask, col] = df_filled.loc[mask, '연도'].map(
            lambda y: chungnam_df.loc[y, col] * ratio if y in chungnam_df.index else None
        )
        
    return df_filled

# 실행
df = round(fill_missing_sejong(sejongdf, target_cols),1)

# 결과 확인 (2015년 데이터가 잘 들어갔는지)
print(df[df['행정구역'] == '세종특별자치시'].head())

[상용월평균급여(원)] 보정 비율: 0.9644
[상용월급여액(원)] 보정 비율: 0.9776
[상용정액급여(원)] 보정 비율: 0.9904
[상용초과급여(원)] 보정 비율: 0.8634
[상용특별급여(원)] 보정 비율: 0.8578
     Unnamed: 0    연도     행정구역  상용월평균급여(원)  상용월급여액(원)  상용정액급여(원)  상용초과급여(원)  \
93            8  2020  세종특별자치시     3755869    3423078    3096090     326989
111          26  2021  세종특별자치시     3845965    3530820    3211675     319145
129          44  2022  세종특별자치시     3983956    3685371    3346826     338545
147           8  2023  세종특별자치시     4096606    3647865    3337418     310447
165          26  2024  세종특별자치시     4331934    3833294    3495015     338279

     상용특별급여(원)
93      332791
111     315145
129     298585
147     448741
165     498640

In [41]:
df[df['행정구역'] != '전국'].to_csv('pre_data/pre_산업일자리_임금수준.csv', index=False)

In [42]:
df4 = pd.read_excel('data/시도_산업별_사업체수_종사자수_및_매출액_2015-2019.xlsx')
df5 = pd.read_excel('data/시도_산업별_사업체수_종사자수_및_매출액_2020-2024.xlsx')

In [43]:
dddf = pd.concat([df4,df5], axis=0, ignore_index=True)
dddf

       연도  행정구역  전체산업사업체수  전체산업종사자수  제조업사업체수  제조업종사자수
0    2015    전국   3874156  20889239   428643  4102259
1    2015    서울    820658   5108828    63389   293173
2    2015    부산    278850   1371843    31458   227632
3    2015    대구    200069    895517    27551   178781
4    2015    인천    186011    984652    24762   245240
..    ...   ...       ...       ...      ...      ...
175  2024  전  북    252411    817157    15002   119854
176  2024  전  남    253206    899604    16143   128939
177  2024  경  북    344568   1283224    33867   317918
178  2024  경  남    403774   1557690    44369   412477
179  2024  제  주    100168    330702     3224    12905

[180 rows x 6 columns]

$$전체산업밀도(천명) = (전체산업사업체수 / 전체산업종사자수) * 1000 $$

In [44]:
dddf.insert(2, '전체산업밀도(천명)', (dddf['전체산업사업체수']/dddf['전체산업종사자수']) * 1000)

In [45]:
dddf['행정구역'] = dddf['행정구역'].str.replace(' ', '')
dddf.replace({'행정구역': sido}, inplace=True)

In [46]:
dddf.insert(2, '통계방식변경', (dddf['연도'] >= 2020).astype(int))

In [47]:
dddf

       연도     행정구역  통계방식변경  전체산업밀도(천명)  전체산업사업체수  전체산업종사자수  제조업사업체수  제조업종사자수
0    2015       전국       0  185.461806   3874156  20889239   428643  4102259
1    2015    서울특별시       0  160.635277    820658   5108828    63389   293173
2    2015    부산광역시       0  203.266700    278850   1371843    31458   227632
3    2015    대구광역시       0  223.411728    200069    895517    27551   178781
4    2015    인천광역시       0  188.910397    186011    984652    24762   245240
..    ...      ...     ...         ...       ...       ...      ...      ...
175  2024  전북특별자치도       1  308.889234    252411    817157    15002   119854
176  2024     전라남도       1  281.463844    253206    899604    16143   128939
177  2024     경상북도       1  268.517422    344568   1283224    33867   317918
178  2024     경상남도       1  259.213322    403774   1557690    44369   412477
179  2024  제주특별자치도       1  302.895054    100168    330702     3224    12905

[180 rows x 8 columns]

In [48]:
dddf[dddf['행정구역'] != '전국'].reset_index(drop=True).to_csv('pre_data/pre_산업일자리_산업밀도.csv')

In [7]:
inderstrydf = pd.read_csv('pre_data/pre_산업일자리_산업밀도.csv', index_col='Unnamed: 0')
inderstrydf.drop(columns=['전체산업밀도(천명)','제조업사업체수'], inplace=True)
inderstrydf.to_csv('pre_data/pre_산업일자리_산업밀도.csv', index=False)