In [1]:
import pandas as pd

In [2]:
df1 = pd.read_excel("C:\project\\busan-ai-agent\\analysis\\notebooks\pre_note\sunjoo\data\교육환경.xlsx")
df1

       연도     행정구역  학교수
0    2025  강원특별자치도   17
1    2024  강원특별자치도   17
2    2023  강원특별자치도   18
3    2022  강원특별자치도   18
4    2021  강원특별자치도   18
..    ...      ...  ...
182  2019     충청북도   18
183  2018     충청북도   18
184  2017     충청북도   17
185  2016     충청북도   17
186  2015     충청북도   17

[187 rows x 3 columns]

In [3]:
df1 = df1.drop(df1[df1["연도"] == 2025].index)

In [4]:
df1

       연도     행정구역  학교수
1    2024  강원특별자치도   17
2    2023  강원특별자치도   18
3    2022  강원특별자치도   18
4    2021  강원특별자치도   18
5    2020  강원특별자치도   18
..    ...      ...  ...
182  2019     충청북도   18
183  2018     충청북도   18
184  2017     충청북도   17
185  2016     충청북도   17
186  2015     충청북도   17

[170 rows x 3 columns]

In [5]:
df2 = pd.read_excel("C:\project\\busan-ai-agent\\analysis\\notebooks\pre_note\sunjoo\data\문화예술_공연시각포함_공연건수.xlsx")
df2

       연도     행정구역  문화예술활동(건)
0    2024     충청북도       1313
1    2023     충청북도       1176
2    2022     충청북도        911
3    2021     충청북도        620
4    2020     충청북도        396
..    ...      ...        ...
165  2019  강원특별자치도        881
166  2018  강원특별자치도       1800
167  2017  강원특별자치도       1567
168  2016  강원특별자치도       1444
169  2015  강원특별자치도       1151

[170 rows x 3 columns]

In [6]:
df3 = pd.read_excel("C:\project\\busan-ai-agent\\analysis\\notebooks\pre_note\sunjoo\data\문화기반시설수.xlsx")
df3

       연도     행정구역  문화기반시설수
0    2015  강원특별자치도      206
1    2015      경기도      492
2    2015     경상남도      190
3    2015     경상북도      196
4    2015    광주광역시       56
..    ...      ...      ...
165  2024     전라남도      240
166  2024  전북특별자치도      188
167  2024  제주특별자치도      126
168  2024     충청남도      199
169  2024     충청북도      142

[170 rows x 3 columns]

In [7]:
df3.dtypes

연도          int64
행정구역       object
문화기반시설수     int64
dtype: object

In [8]:
# df = pd.concat([df1, df2['문화예술활동(건)'], df3['문화기반시설수']], axis=1)
# df
# out = pd.merge(df1, df2, df3, on=["연도", "행정구역"], how="how")

from functools import reduce
import pandas as pd

df_merged = reduce(
    lambda left, right: pd.merge(left, right, on=["연도", "행정구역"], how="left"),
    [df1, df2, df3])
df_merged

       연도     행정구역  학교수  문화예술활동(건)  문화기반시설수
0    2024  강원특별자치도   17       1767      247
1    2023  강원특별자치도   18       1580      247
2    2022  강원특별자치도   18       1020      246
3    2021  강원특별자치도   18        881      241
4    2020  강원특별자치도   18        530      235
..    ...      ...  ...        ...      ...
165  2019     충청북도   18        620      136
166  2018     충청북도   18        882      130
167  2017     충청북도   17        706      128
168  2016     충청북도   17        688      126
169  2015     충청북도   17        631      126

[170 rows x 5 columns]

In [9]:
df_merged.to_excel("merged.xlsx", index=False)

In [10]:
df_merged=df_merged[df_merged.isna().any(axis=1)]
df_merged

Empty DataFrame
Columns: [연도, 행정구역, 학교수, 문화예술활동(건), 문화기반시설수]
Index: []

In [11]:
df4 = pd.read_excel("C:\project\\busan-ai-agent\\analysis\\notebooks\pre_note\\nari\data\시도별_경제활동별_지역내총생산.xlsx")
df4

       연도     행정구역     지역내총생산
0    2015    서울특별시  386818107
1    2015    부산광역시   88748972
2    2015    대구광역시   56003260
3    2015    인천광역시   81805340
4    2015    광주광역시   37243072
..    ...      ...        ...
165  2024  전북특별자치도   66792381
166  2024     전라남도  103970897
167  2024     경상북도  134698401
168  2024     경상남도  151241350
169  2024  제주특별자치도   26928491

[170 rows x 3 columns]

In [12]:
df5 = pd.read_excel("C:\project\\busan-ai-agent\\analysis\\notebooks\pre_note\\nari\data\재정자립도당초시도별.xlsx")
df5

       연도     행정구역  자체수입(백만원)  자치단체_예산규모(백만원)  재정자립도(%)
0    2015    서울특별시   15653529        19495264     80.29
1    2015    부산광역시    3872021         7594399     50.99
2    2015    대구광역시    2467709         5265313     46.87
3    2015    인천광역시    3514676         5942377     59.15
4    2015    광주광역시    1424994         3222999     44.21
..    ...      ...        ...             ...       ...
182  2025  전북특별자치도    3724601        15755912     23.64
183  2025     전라남도    4410315        18641017     23.66
184  2025     경상북도    5788006        23773956     24.35
185  2025     경상남도    7195613        20976631     34.30
186  2025  제주특별자치도    1994784         6031686     33.07

[187 rows x 5 columns]

In [13]:
# df5 = df5.rename(columns={"년도":"연도"})
# df5 = df5.drop(df5[df5["연도"] == 2025].index)
# df5

In [14]:
df5_sel = df5[['연도', '행정구역', '재정자립도(%)']]
df5_sel

       연도     행정구역  재정자립도(%)
0    2015    서울특별시     80.29
1    2015    부산광역시     50.99
2    2015    대구광역시     46.87
3    2015    인천광역시     59.15
4    2015    광주광역시     44.21
..    ...      ...       ...
182  2025  전북특별자치도     23.64
183  2025     전라남도     23.66
184  2025     경상북도     24.35
185  2025     경상남도     34.30
186  2025  제주특별자치도     33.07

[187 rows x 3 columns]

In [15]:
from functools import reduce
import pandas as pd

df_merged = reduce(
    lambda left, right: pd.merge(left, right, on=["연도", "행정구역"], how="left"),
    [df1, df2, df3, df4, df5_sel])
df_merged

       연도     행정구역  학교수  문화예술활동(건)  문화기반시설수    지역내총생산  재정자립도(%)
0    2024  강원특별자치도   17       1767      247  64615611     25.22
1    2023  강원특별자치도   18       1580      247  62160748     25.42
2    2022  강원특별자치도   18       1020      246  57723494     24.69
3    2021  강원특별자치도   18        881      241  55267031     24.52
4    2020  강원특별자치도   18        530      235  51573015     25.75
..    ...      ...  ...        ...      ...       ...       ...
165  2019     충청북도   18        620      136  76210571     28.74
166  2018     충청북도   18        882      130  74435481     29.61
167  2017     충청북도   17        706      128  69598516     30.05
168  2016     충청북도   17        688      126  63793617     28.76
169  2015     충청북도   17        631      126  58256451     28.14

[170 rows x 7 columns]

In [16]:
df6 = pd.read_csv("C:\project\\busan-ai-agent\\analysis\\notebooks\pre_note\seoha\data\인구총조사_19-39_2015-2024.csv")
df6['청년총인구수'] = df6[["19세","20~24세","25~29세","30~34세","35~39세"]].sum(axis=1)
df6

       연도     행정구역     19세   20~24세   25~29세   30~34세   35~39세    청년총인구수
0    2015       전국  671216  3385936  3027896  3611034  3783589  14479671
1    2015    서울특별시  121531   681199   722350   823935   767625   3116640
2    2015    부산광역시   48246   241138   203729   232762   240788    966663
3    2015    대구광역시   35472   175680   141245   159794   175062    687253
4    2015    인천광역시   36518   195760   180149   215364   225552    853343
..    ...      ...     ...      ...      ...      ...      ...       ...
175  2024  전북특별자치도   15725    90731    91785    86910    80797    365948
176  2024     전라남도   10266    69515    84588    82877    78696    325942
177  2024     경상북도   20579   115516   122422   125646   123466    507629
178  2024     경상남도   21188   131838   156211   167753   168782    645772
179  2024  제주특별자치도    4473    28706    35505    38543    36387    143614

[180 rows x 8 columns]

In [17]:
df6_sel=df6[['연도', '행정구역', '청년총인구수']]
df6_sel

       연도     행정구역    청년총인구수
0    2015       전국  14479671
1    2015    서울특별시   3116640
2    2015    부산광역시    966663
3    2015    대구광역시    687253
4    2015    인천광역시    853343
..    ...      ...       ...
175  2024  전북특별자치도    365948
176  2024     전라남도    325942
177  2024     경상북도    507629
178  2024     경상남도    645772
179  2024  제주특별자치도    143614

[180 rows x 3 columns]

In [18]:
df7 = pd.read_csv("C:\project\\busan-ai-agent\\analysis\\notebooks\pre_note\seoha\data\주민등록연앙인구_2015-2024.csv")
df7

       연도     행정구역    연앙인구수(명)   연앙인구수(천명)
0    2015       전국  50951719.0  50951.7190
1    2015    서울특별시   9907155.0   9907.1550
2    2015    부산광역시   3478811.5   3478.8115
3    2015    대구광역시   2471181.5   2471.1815
4    2015    인천광역시   2886542.0   2886.5420
..    ...      ...         ...         ...
175  2024  전북특별자치도   1741636.0   1741.6360
176  2024     전라남도   1792325.0   1792.3250
177  2024     경상북도   2535499.0   2535.4990
178  2024     경상남도   3229883.0   3229.8830
179  2024  제주특별자치도    669051.0    669.0510

[180 rows x 4 columns]

In [19]:
# from functools import reduce
# import pandas as pd

# df_merged = reduce(
#     lambda left, right: pd.merge(left, right, on=["연도", "행정구역"], how="left"),
#     [df1, df2, df3, df4, df5_sel, df6_sel])
# df_merged

In [20]:
df8 = pd.read_csv("C:\project\\busan-ai-agent\\analysis\\notebooks\pre_note\haeseong\\5인이상사업체상용근로자월평균급여.csv")
df8

,Unnamed: 0,연도,행정구역,상용월평균급여(원),상용월급여액(원),상용정액급여(원),상용초과급여(원),상용특별급여(원)
0,0,2015,전국,3304864,2926186,2710026,216160,378678
1,1,2015,서울특별시,3708005,3261561,3169585,91976,446444
2,2,2015,부산광역시,2916010,2620611,2446981,173631,295399
3,3,2015,대구광역시,2678424,2415995,2231900,184095,262429
4,4,2015,인천광역시,3025075,2723424,2499996,223427,301651
...,...,...,...,...,...,...,...,...
188,49,2025,전북특별자치도,3815150,3475789,3202598,273191,339361
189,50,2025,전라남도,4250496,3791086,3484960,306126,459410
190,51,2025,경상북도,4352224,3920655,3531001,389654,431569
191,52,2025,경상남도,4260901,3906168,3518751,387417,354733
192,53,2025,제주특별자치도,3575691,3289535,3148603,140932,286156

In [22]:
df = pd.read_csv('C:\project\\busan-ai-agent\\analysis\\notebooks\pre_note\seoha\data\주민등록연앙인구_2015-2024.csv')
df

       연도     행정구역    연앙인구수(명)   연앙인구수(천명)
0    2015       전국  50951719.0  50951.7190
1    2015    서울특별시   9907155.0   9907.1550
2    2015    부산광역시   3478811.5   3478.8115
3    2015    대구광역시   2471181.5   2471.1815
4    2015    인천광역시   2886542.0   2886.5420
..    ...      ...         ...         ...
175  2024  전북특별자치도   1741636.0   1741.6360
176  2024     전라남도   1792325.0   1792.3250
177  2024     경상북도   2535499.0   2535.4990
178  2024     경상남도   3229883.0   3229.8830
179  2024  제주특별자치도    669051.0    669.0510

[180 rows x 4 columns]

In [35]:
# 최종 데이터 저장
df.to_excel(
    'data/people.xlsx',
    index=False,
    # encoding='utf-8-sig'
)
# 최종 데이터 저장
# df.to_csv(
#     'data/busan_youth_v3.xlsx',
#     index=False,
#     encoding='utf-8-sig'
# )