In [2]:
import numpy as np
import pandas as pd

In [2]:
# Gross Regional Domestic Product: 지역내총생산
regional_gdp = pd.read_excel('C:/project/busan-ai-agent/analysis/notebooks/pre_note/nari/data/시도별_경제활동별_지역내총생산.xlsx')
regional_gdp

       연도     행정구역     지역내총생산
0    2015    서울특별시  386818107
1    2015    부산광역시   88748972
2    2015    대구광역시   56003260
3    2015    인천광역시   81805340
4    2015    광주광역시   37243072
..    ...      ...        ...
165  2024  전북특별자치도   66792381
166  2024     전라남도  103970897
167  2024     경상북도  134698401
168  2024     경상남도  151241350
169  2024  제주특별자치도   26928491

[170 rows x 3 columns]

In [3]:
# Fiscal Self-Reliance : 재정자립도
fsr_init = pd.read_excel('C:/project/busan-ai-agent/analysis/notebooks/pre_note/nari/data/재정자립도당초시도별.xlsx')
fsr_init

       연도     행정구역  자체수입(백만원)  자치단체_예산규모(백만원)  재정자립도(%)
0    2015    서울특별시   15653529        19495264     80.29
1    2015    부산광역시    3872021         7594399     50.99
2    2015    대구광역시    2467709         5265313     46.87
3    2015    인천광역시    3514676         5942377     59.15
4    2015    광주광역시    1424994         3222999     44.21
..    ...      ...        ...             ...       ...
182  2025  전북특별자치도    3724601        15755912     23.64
183  2025     전라남도    4410315        18641017     23.66
184  2025     경상북도    5788006        23773956     24.35
185  2025     경상남도    7195613        20976631     34.30
186  2025  제주특별자치도    1994784         6031686     33.07

[187 rows x 5 columns]

In [4]:
merged_df = pd.merge(
    regional_gdp,
    fsr_init,
    on=["연도", "행정구역"],
    how="left"
)
merged_df

       연도     행정구역     지역내총생산  자체수입(백만원)  자치단체_예산규모(백만원)  재정자립도(%)
0    2015    서울특별시  386818107   15653529        19495264     80.29
1    2015    부산광역시   88748972    3872021         7594399     50.99
2    2015    대구광역시   56003260    2467709         5265313     46.87
3    2015    인천광역시   81805340    3514676         5942377     59.15
4    2015    광주광역시   37243072    1424994         3222999     44.21
..    ...      ...        ...        ...             ...       ...
165  2024  전북특별자치도   66792381    3526859        15004158     23.51
166  2024     전라남도  103970897    4375201        17930398     24.40
167  2024     경상북도  134698401    5546267        22578779     24.56
168  2024     경상남도  151241350    6881650        20462808     33.63
169  2024  제주특별자치도   26928491    1931686         5680142     34.01

[170 rows x 6 columns]

In [8]:
youth = pd.read_csv('../../data/busan_youth_v1.csv', index_col='Unnamed: 0')
youth

,연도,행정구역,연앙인구수(명),연앙인구수(천명),지역내총생산,재정자립도(%),통계방식변경,전체산업사업체수,전체산업종사자수,제조업종사자수,상용월평균급여(원),학교수,문화기반시설수,문화예술활동(건),19세,20~24세,25~29세,30~34세,35~39세
0,2015,강원특별자치도,1533360.0,1533.3600,41872021.0,21.45,0.0,133517.0,580331.0,56047.0,2884859.0,19.0,206.0,1151.0,21687.0,104816.0,76777.0,85868.0,95961.0
1,2015,경기도,12337489.0,12337.4890,404868209.0,60.72,0.0,827983.0,4650266.0,1260761.0,3193960.0,78.0,492.0,3815.0,157674.0,804648.0,731217.0,904071.0,993964.0
2,2015,경상남도,3336798.5,3336.7985,109028154.0,37.43,0.0,262947.0,1365595.0,444673.0,3140398.0,24.0,190.0,1801.0,38635.0,194204.0,168655.0,221650.0,243328.0
3,2015,경상북도,2684089.5,2684.0895,109563894.0,24.26,0.0,218795.0,1066259.0,328305.0,3186263.0,39.0,196.0,1021.0,35122.0,162946.0,136521.0,163734.0,172486.0
4,2015,광주광역시,1465091.0,1465.0910,37243072.0,44.21,0.0,113424.0,559853.0,82540.0,2916828.0,18.0,56.0,1168.0,23947.0,114226.0,89544.0,107109.0,115620.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,2025,전라남도,NaN,NaN,NaN,23.66,NaN,NaN,NaN,NaN,4250496.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193,2025,전북특별자치도,NaN,NaN,NaN,23.64,NaN,NaN,NaN,NaN,3815150.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,2025,제주특별자치도,NaN,NaN,NaN,33.07,NaN,NaN,NaN,NaN,3575691.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,2025,충청남도,NaN,NaN,NaN,32.22,NaN,NaN,NaN,NaN,4812230.0,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,2025,충청북도,NaN,NaN,NaN,31.83,NaN,NaN,NaN,NaN,4068182.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN